name: practica_env
on: [pull_request, push]
env:
  API_KEY: ARXPZTFVLGRIJK

  jobs1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "The API key is:${{env.API_KEY}}"
  jobs2:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "The API key is:$API_KEY"


